//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Adminstradador.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class Adminstradador extends Logavel, Autenticavel {
	public void cadastrarSecretarios(Secretario secretario) {
	
	}
	
	public void cadastrarCorretor(Corretor corretor) {
	
	}
}
