//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Autenticavel.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public abstract class Autenticavel extends Pessoa {
	public void logar(String login, String senha) {
	
	}
}
