//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cliente.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class Cliente extends Pessoa {
	private int numeroContaBancaria;
}
