//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Corretor.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class Corretor extends Pessoa, Secretario {
	public void vender(ImovelVenda imovel, Cliente comprador) {
	
	}
	
	public void alugar(Locatorio locatario, ImovelAluguel imovel) {
	
	}
}
