//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ImovelVenda.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class ImovelVenda extends Imovel {
	public double preco;
}
