//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ImovelAluguel.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class ImovelAluguel extends Imovel {
	public double mensalidade;
	public String fimContrato;
}
