//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Imovel.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class Imovel {
	public String endereco;
	public double area;
	public String tipo;
	public int numeroDeQuartos;
	public int numeroDeBanheiros;
	public boolean temGaragem;
	public String contrato;
	public String estado;
	public List<Visita> visitasAgendadas;
	public boolean vendaEAluguel;
}
