//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Locatario.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class Locatario extends Cliente {
}
