//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Logavel.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public interface Logavel {
	public void logar(String login, String senha);
}
