//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pessoa.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public abstract class Pessoa {
	protected String nome;
	protected String cpf;
	protected String rg;
	protected String endereco;
	protected String telefone;
}
