//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Secretario.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class Secretario extends Pessoa, Logavel, Autenticavel {
	private String horaDeEntrada;
	private String horaDeSaida;
	public void cadastrarCliente(Cliente cliente) {
	
	}
	
	public void cadastrarImovel(Imovel imovel) {
	
	}
	
	public void receberMensalidade(Locatario locatario) {
	
	}
	
	public void listarImovel() {
	
	}
	
	public void gerarRelatorio(Cliente cliente) {
	
	}
	
	public void gerarRelatorio(Imovel imovel) {
	
	}
	
	public void gerarRelatorio(Corretor corretor) {
	
	}
	
	public void agendarVisita(Cliente cliente, Imovel imovel) {
	
	}
}
