//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Visita.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class Visita {
	public Date data;
	public Cliente cliente;
}
